### ISSUE TITLE
Provide img

### ISSUE THREAD

**Issue by soryncrash13** [Murii/anim_clove#1]
Hi my friend. Can you provide 1 or 2 photos of the output of anim.lsp? In a folder with the name of "Img anim.lsp" for example. Thank you, for showing da wey :uganda:

**Comment by Murii** [comment]
Hello, showing pictures of the animation system is not possible because I'd just capture frames of that animation, instead I can try and provide a .GIF.

**Comment by soryncrash13** [comment]
Yes please kind sir. I'd be greatful to the bones. 🗡  🤣
